In [21]:
import numpy as np

#Absolute value
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [22]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [23]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [24]:
x=np.array([3-4j,4-3j,2+0j,0+1j]) 
np.abs(x)


array([5., 5., 2., 1.])

In [26]:
#Trigonometric functions
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta) 
print("sin(theta) = ", np.sin(theta)) 
print("cos(theta) = ", np.cos(theta)) 
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [27]:
#Exponents and logarithms
x = [1, 2, 3] 
print("x =", x)
print("e^x =",np.exp(x)) 
print("2^x =",np.exp2(x)) 
print("3^x =",np.power(3,x))


x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [28]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x)) 
print("log2(x) =", np.log2(x)) 
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [37]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y) 
print(y)

[ 0. 10. 20. 30. 40.]


In [39]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]
